### ISSUE TITLE
Improved Patch Notes

### ISSUE THREAD

**Issue by Saphnx** [PeterKelemen2/GameplayTimeTracker#1]
Hey, first I just want to say I love the app! Nice work =)

I just updated to 1.3.1 and my heart sank when all the times appeared changed. After a few seconds, I realised it was displaying the minutes as hours, so thought perhaps a bug was introduced. Naturally, I came here to look at the code to see if I could spot the issue and that's when I came across the update legacy times feature you'd introduced (all updated now thanks).

I can see you've put a note on the readme, but I think that's a little hidden (at least it was for me) as existing users are unlikely to re-read the readme. Perhaps in future releases, you could specify all changes and explicitly call out anything that requires user interaction? You could also look to auto-convert legacy formats by checking the client version at startup and converting as necessary (of course by taking a backup of their data first).

Anyway, great app and look forward to seeing how it progresses.

Happy holidays! =)

**Comment by PeterKelemen2** [comment]
Hey there!

Thank you for your feedback! I am happy to hear that it's working out for you.

I was actually thinking about some way to automatically update the time from the "old" data, getting this indication from the version would be a great way, thank you for suggesting.
I am still pretty new to this and looking forward to improving, still trying to iron out some issues. I will be more attentive towards informing about the release changes.
I highly recommend not pressing the button again, since it will convert it once again. There is no fix for that as of now, because I have limited time for the app right now, but I'm working on it!

Happy holidays for you too!
